### PR TITLE
My First Project: Embedding Images and Video

### PR DESCRIPTION
**Pull request by Albertino2020**
This project was supposed to be collaborative and, in fact, it was so in its first 3,5 hours. Due to the absence of my coding partner since then, I have been working on it alone.
I used only HTML tags, elements and CSS styles I learned in the process and tried to do thins using different tactics to achieve the same goal, i.e., I tried not to copy and paste code, but create my own to better understand and master embedding images and video, in particular, and HTML and CSS at large.

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team      
#### Great Job so far, but there are a few more things required. 
## Required Changes:
#### General 
- [x]  Your README.md is not descriptive https://github.com/microverseinc/readme-template
- [x] The search button should be a search bar, not text 
- [x] The share should be a button
- [x] The subscribe should be a button not image 
- [x] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload
- [x] The three images on the right of the search button should look similar to images in the original site 
- [x] Please ensure Each section (video, comments, sidebar, navigation bar) has it's own container (<div> or similar)
- [x] Kindly note that nav should be used only for navigation bar
### Make changes and submit another code review request.
*Happy coding*

**Comment by Albertino2020** [comment]
Thanks, @akobiyoyo for the review and the remarks!

Changes will be made today.

Kind regards,

Albertino
________________________________
De: Desmond Chubiyojo Adama <notifications@github.com>
Enviado: 26 de fevereiro de 2020 20:51
Para: Albertino2020/Youtube-homepage <Youtube-homepage@noreply.github.com>
Cc: Albertino Francisco <albertino@ua.pt>; Author <author@noreply.github.com>
Assunto: Re: [Albertino2020/Youtube-homepage] My First Project: Embedding Images and Video (#3)


@kobiyoyo requested changes on this pull request.

Hi Team [https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png] <https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png>
Great Job so far, but there are a few more things required.
Required Changes:
General

  *   Your README.md is not descriptive https://github.com/microverseinc/readme-template
  *   The search button should be a search bar not text
  *   The share should be a button
  *   The subscribe should be a button not image
  *   Check HTML markup with this validator https://validator.w3.org/#validate_by_upload
  *   The Three images on the right of the search button should look similar to images in the original site
  *   Please ensure Each section (video, comments, sidebar, navigation bar) has it's own container (
or similar)
  *   Kindly note that nav should be used only for navigation bar

Make changes and submit another code review request.

Happy coding

**Review by MarioDena — COMMENTED** [review]
Hello! My name is Mario. 😄 

Congratulations on your project! I can see you dedicated passion and time!! 👏 👏 
However there are still some mistakes we need to fix.

## Changes Required ❗️ 

- [x] Your branch have a conflicting file `README.md` please fix the conflicts before merging. (This is due to changes made on different branches at different times without updating) Read this article if you need help fixing the conflicts: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line

__BE VERY CAREFUL TO NOT DELETE THE UPDATED README.__

- [x] The search bar should be centered on your top navbar. Right now its tilted to the left. (If it looks centered on your screen please use the developer tools to check your project on different resolutions).

## Optional changes

- [ ] Work on your design a little bit more, right now even if the project does cover the minimum requirements your design looks very different from original youtube. I would recommend trying to work on the small details to make it look closer to the original. For example: font and icons sizes, color distribution, spacing for your elements. __This is [OPTIONAL]__ 

- [ ] Try to format your code with a code formater for HTML and CSS right now you have a lot of empty spaces and new lines that affect the readability of your files.  __This is [OPTIONAL]__ 


 After making the required changes please resubmit your project for review.

## Code review by Mario Enrique Delgado Naranjo

**Comment by uryelah** [comment]
Hello **Albertino**, I'm Sarah, your reviewer for this PR . 👩‍🚀 👋 

I see that you had some issues with conflicts in your PR and that you closed the #3 PR.
When this happens **please don't make another PR, request the next code review at the first PR.** 

The previous reviewer only marked as required the solving of the conflict, if you had issues with that take a moment to[ read this guide](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github). 

-----

### Congrats on your first Microverse Project! 🎉 

### Status Approved

You may close this PR, resolve the conflicts and merge it.

Before you do that though, please consider working in the optional changes from the last TSE, on the page styling and similarity to the original.

In the next clone projects, it will be very important for you to be able to copy the original page look as closely as you can because that gives us a way to better assess your learning.

Being creative is awesome, and you'll have opportunities in the future to exercise your own design choices, but right now focus on the HTML and CSS building blocks. See it as a client giving you a design and asking you to make it into code, in this situation **following the guide design is the main part of the job.**

-------

### Optional Changes

- [ ]  Format your HTML and CSS files for a tidy and easy to read project

- [ ] Remove the extra elements that are not found in the original page. Ex: the fixed red footer.

-------

**Good job and keep it up for the next projects!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Pull request merged**
